export let paperData = [
    [],
    [
        {id:139,title:'Dantzig-Wolfe Decomposition for Cost Partitioning',authors:'Florian Pommerening, Thomas Keller, Valentina Halasi, Jendrik Seipp, Silvan Sievers and Malte Helmert',keywords:'cost partitioning'},
        {id:153,title:'Exploiting Cyclic Dependencies in Landmark Heuristics',authors:'Clemens Büchner, Thomas Keller and Malte Helmert',keywords:'optimal planning'},
        {id:230,title:'Subset-Saturated Transition Cost Partitioning',authors:'Dominik Drexler, Jendrik Seipp and David Speck',keywords:'Optimal Classical Planning'},
        {id:287,title:'Online Saturated Cost Partitioning for Classical Planning',authors:'Jendrik Seipp',keywords:'optimal classical planning'},
    ],
    [
        {id:151,title:'On the Compilability and Expressive Power of State-Dependent Action Costs',authors:'David Speck, David Borukhson, Robert Mattmüller and Bernhard Nebel',keywords:'classical planning'},
        {id:152,title:'Learning Heuristic Selection with Dynamic Algorithm Configuration',authors:'David Speck, André Biedenkapp, Frank Hutter, Robert Mattmüller and Marius Lindauer',keywords:'satisficing planning'},
        {id:282,title:'Automatic Instance Generation for Classical Planning',authors:'Álvaro Torralba, Jendrik Seipp and Silvan Sievers',keywords:'classical planning'},
        {id:368,title:'Computational Complexity of Computing Symmetries in Finite-Domain Planning',authors:'Alexander Shleyfman and Peter Jonsson',keywords:''},
    ],
    [
        {id:36,title:'Iterative-deepening Bidirectional Heuristic Search with Restricted Memory',authors:'Shahaf Shperberg, Steven Danishevski, Ariel Felner and Nathan Sturtevant',keywords:'Bidirectional heuristic search'},
        {id:128,title:'Delete-Relaxation Heuristics for Lifted Classical Planning',authors:'Augusto B. Corrêa, Guillem Francès, Florian Pommerening and Malte Helmert',keywords:'lifted planning'},
        {id:146,title:'Endomorphisms of Lifted Planning Problems',authors:'Rostislav Horcik and Daniel Fišer',keywords:'Lifted pruning'},
        {id:322,title:'Hierarchical Width-Based Planning and Learning',authors:'Miquel Junyent, Vicenç Gómez and Anders Jonsson',keywords:'Hierarchical planning'},
    ],
    [
        {id:17,title:'Approximate bi-criteria search by efficient representation of subsets of the Pareto-optimal frontier',authors:'Oren Salzman and Boris Goldin',keywords:'Bicriteria search'},
        {id:61,title:'Conflict-Free Multi-Agent Meeting',authors:'Dor Atzmon, Shahar Idan Freiman, Oscar Epshtein, Oran Shichman and Ariel Felner',keywords:'Conflict-Free Multi-Agent Meeting'},
        {id:99,title:'OMCoRP: An Online Mechanism for Competitive Robot Prioritization',authors:'Sankar Das, Swaprava Nath and Indranil Saha',keywords:'Multi-Robot System'},
        {id:366,title:'Safe Multi-Agent Pathfinding with Time Uncertainty',authors:'Tomer Shahar, Shashank Shekhar, Dor Atzmon, Abdallah Saffidine, Brendan Juba and Roni Stern',keywords:''},
    ],
    [
        {id:191,title:'A Competitive Analysis of Online Multi-Agent Path Finding',authors:'Hang Ma',keywords:'multi-agent path finding'},
        {id:345,title:'Conflict-Based Increasing Cost Search',authors:'Thayne T. Walker, Nathan Sturtevant, Han Zhang, Jiaoyang Li, Sven Koenig, Ariel Felner and T. K. Satish Kumar',keywords:'multi-agent'},
        {id:353,title:'Speeding Up Search-Based Motion Planning using Expansion Delay Heuristics',authors:'Jasmeet Kaur, Ishani Chatterjee and Maxim Likhachev',keywords:'Learning Heuristics'},
        {id:165,title:'Scalable Rail Planning and Replanning: Winning the 2020 Flatland Challenge',authors:'Jiaoyang Li, Zhe Chen, Yi Zheng, Shao-Hung Chan, Daniel Harabor, Peter J. Stuckey, Hang Ma and Sven Koenig',keywords:'Multi-agent path finding'},
    ],
    [
        {id:34,title:'Jump Point Search with Temporal Obstacles',authors:'Shuli Hu, Daniel Harabor, Graeme Gange, Peter Stuckey and Nathan Sturtevant',keywords:'heuristic'},
        {id:123,title:'Width-Based Backward Search',authors:'Chao Lei and Nir Lipovetzky',keywords:'classical planning'},
        {id:140,title:'The Consistent Case in Bidirectional Search and a Bucket-to-Bucket Algorithm as a Middle Ground between Front-to-End and Front-to-Front',authors:'Vidal Alcázar',keywords:'bidirectional'},
        {id:206,title:'Contracting and Compressing Shortest Path Databases',authors:'Bojie Shen, Muhammad Aamir Cheema, Daniel Harabor and Peter Stuckey',keywords:'Shortest Path'},
    ],
    [
        {id:67,title:'E2Coop: Energy Efficient and Cooperative Obstacle Detection and Avoidance for UAV Swarms',authors:'Shuangyao Huang, Haibo Zhang and Zhiyi Huang',keywords:'PSO'},
        {id:84,title:'Hierarchical Freespace Planning for Navigation in Unfamiliar Worlds',authors:'Raj Korpan and Susan Epstein',keywords:'hierarchical path planning'},
        {id:187,title:'Approximate Novelty Search',authors:'Anubhav Singh, Nir Lipovetzky, Miquel Ramirez and Javier Segovia',keywords:'AI Planning'},
        {id:297,title:'S*: A Heuristic Information-Based Approximation Framework for Multi-Goal Path Finding',authors:'Kenny Chour, Sivakumar Rathinam and R Ravi',keywords:'Minimum Cost Path Problem'},
    ],
    [
        {id:145,title:'Predicted Composite Signed-Distance Fields for Real-Time Motion Planning in Dynamic Environments',authors:'Mark Finean, Wolfgang Merkt and Ioannis Havoutis',keywords:'Motion and path planning'},
        {id:209,title:'Towards Time-Optimal Any-Angle Path Planning With Dynamic Obstacles',authors:'Konstantin Yakovlev and Anton Andreychuk',keywords:'path planning'},
        {id:222,title:'Improving AlphaZero Using Monte-Carlo Graph Search',authors:'Johannes Czech, Patrick Korus and Kristian Kersting',keywords:'Monte-Carlo Tree Search'},
        {id:363,title:'Attributed Transition-based Domain Control Knowledge for Domain-Independent Planning',authors:'Lukas Chrpa, Roman Barták, Jindřich Vodrážka and Marta Vomlelová',keywords:''},
    ],
    [
        {id:4,title:'Task-Aware Waypoint Sampling for Robotic Planning',authors:'Sarah Keren, Gerard Canal and Michael Cashmore',keywords:'Task and motion planning'},
        {id:76,title:'Verifying Plans and Scripts for Robotics Tasks Using Performance Level Profiles',authors:'Alexander Kovalchuk, Shashank Shekhar and Ronen Brafman',keywords:'Plan verification'},
        {id:261,title:'In-Station Train Dispatching: A PDDL+ Planning Approach',authors:'Matteo Cardellini, Marco Maratea, Mauro Vallati, Gianluca Boleto and Luca Oneto',keywords:'In-Station Train Dispatching'},
        {id:309,title:'Non-Deterministic Conformant Planning Using a Counterexample-Guided Incremental Compilation to Classical Planning',authors:'Alban Grastien and Enrico Scala',keywords:'Conformant planning'},
    ],
    [
        {id:132,title:'Flexible FOND Planning with Explicit Fairness Assumptions',authors:'Ivan Rodriguez, Blai Bonet, Sebastian Sardina and Hector Geffner',keywords:'FOND planning'},
        {id:134,title:'Pattern Databases for Goal-Probability Maximization in Probabilistic Planning',authors:'Thorsten Klößner, Álvaro Torralba, Marcel Steinmetz and Jörg Hoffmann',keywords:'Probabilistic Planning'},
        {id:274,title:'Rule-based shielding for Partially Observable Monte-Carlo Planning',authors:'Giulio Mazzi, Alberto Castellini and Alessandro Farinelli',keywords:'POMDPs'},
        {id:370,title:'Selecting goals in oversubscription planning using relaxed plans',authors:'Angel Garcia-Olaya, Tomas De La Rosa and Daniel Borrajo',keywords:''},
    ],
    [
        {id:147,title:'Data-Driven Decision-Theoretic Planning using Recurrent Sum-Product-Max Networks',authors:'Hari Tatavarti, Prashant Doshi and Layton Hayes',keywords:'machine learning'},
        {id:305,title:'Multiple Plans are Better than One: Diverse Stochastic Planning',authors:'Mahsa Ghasemi, Evan Scope Crafts, Bo Zhao and Ufuk Topcu',keywords:'Stochastic Planning'},
    ],
    [
        {id:79,title:'Robust Opponent Modeling via Adversarial Ensemble Reinforcement Learning',authors:'Macheng Shen and Jonathan How',keywords:'Opponent modeling'},
        {id:201,title:'Learning and Exploiting Shaped Reward Models for Large Scale Multiagent RL',authors:'Arambam James Singh, Akshat Kumar and Hoong Chuin Lau',keywords:'Multiagent Sequential Decision Making'},
        {id:208,title:'Integrating Knowledge Compilation with Reinforcement Learning for Routes',authors:'Jiajing Ling, Kushagra Chandak and Akshat Kumar',keywords:'multiagent sequential decision making'},
        {id:180,title:'DeepFreight: A Model-free Deep-reinforcement-learning-based Algorithm for Multi-transfer Freight Delivery',authors:'Jiayu Chen, Abhishek K. Umrawal, Tian Lan and Vaneet Aggarwal',keywords:'Multi-agent Reinforcement Learning'},
    ],
    [
        {id:86,title:'Guiding Robot Exploration in Reinforcement Learning via Automated Planning',authors:'Yohei Hayamizu, Saeid Amiri, Kishan Chandan, Keiki Takadama and Shiqi Zhang',keywords:'Reinforcement Learning'},
        {id:190,title:'A Simulator-based Planning Framework for Optimizing Autonomous Greenhouse Control Strategy',authors:'Zhicheng An, Xiaoyan Cao, Yao Yao, Wanpeng Zhang, Lanqing Li, Yue Wang, Shihui Guo and Dijun Luo',keywords:'Simulator-based planning'},
        {id:354,title:'A Deep Ensemble Method for Multi-Agent Reinforcement Learning: A Case Study on Air Traffic Control',authors:'Supriyo Ghosh, Sean Laguna, Shiau Hong Lim, Laura Wynter and Hasan Poonawala',keywords:'Reinforcement Learning'},
        {id:360,title:'Constrained Multiagent Markov Decision Processes: a Taxonomy of Problems and Algorithms',authors:'Frits de Nijs, Erwin Walraven, Mathijs De Weerdt and Matthijs T. J. Spaan',keywords:''},
    ],
    [
        {id:24,title:'Situated Temporal Planning Using Deadline-aware Metareasoning',authors:'Shahaf Shperberg, Andrew Coles, Erez Karpas, Wheeler Ruml and Solomon Eyal Shimony',keywords:'Metareasoning'},
        {id:144,title:'Abstraction-Guided Policy Recovery from Expert Demonstrations',authors:'Canmanie T. Ponnambalam, Frans A. Oliehoek and Matthijs T. J. Spaan',keywords:'imitation learning'},
        {id:215,title:'Translations from Discretised PDDL+ to Numeric Planning',authors:'Francesco Percassi, Enrico Scala and Mauro Vallati',keywords:'Hybrid PDDL+ Planning'},
        {id:273,title:'Meta Reinforcement Learning for Heuristic Planing',authors:'Ricardo Luna Gutierrez and Matteo Leonetti',keywords:'heuristic planning'},
    ],
    [
        {id:55,title:'RePReL: Integrating Relational Planning and Reinforcement Learning for Effective Abstraction',authors:'Harsha Kokel, Arjun Manoharan, Sriraam Natarajan, Balaraman Ravindran and Prasad Tadepalli',keywords:'Reinforcement Learning'},
        {id:120,title:'LM-cut and Operator Counting Heuristics for Optimal Numeric Planning with Simple Conditions',authors:'Ryo Kuroiwa, Alexander Shleyfman, Chiara Piacentini, Margarita Castro and J. Christopher Beck',keywords:'numeric planning'},
        {id:257,title:'Privacy-Preserving Algorithm for Decoupling of Multi-Agent Plans with Uncertainty',authors:'Yuening Zhang and Brian Williams',keywords:'temporal network'},
        {id:312,title:'Blind Decision Making: Reinforcement Learning with Delayed Observations',authors:'Mridul Agarwal and Vaneet Aggarwal',keywords:'Reinforcement Learning'},
    ],
    [
        {id:300,title:'Automated Production Scheduling for Artificial Teeth Manufacturing',authors:'Felix Winter, Christoph Mrkvicka, Nysret Musliu and Jakob Preininger',keywords:'machine scheduling'},
        {id:325,title:'Scheduling with Complete Multipartite Incompatibility Graph on Parallel Machines',authors:'Tytus Pikies, Krzysztof Turowski and Marek Kubale',keywords:'job scheduling'},
        {id:328,title:'Total Completion Time Minimization for Scheduling with Incompatibility Cliques',authors:'Klaus Jansen, Alexandra Lassota, Marten Maack and Tytus Pikies',keywords:'identical machines'},
        {id:361,title:'Constraint-based Scheduling for Paint Shops in the Automotive Supply Industry',authors:'Felix Winter and Nysret Musliu',keywords:''},
    ],
    [
        {id:54,title:'Distributed Fair Scheduling for Information Exchange in Multi-Agent Systems',authors:'Majid Raeis and S. Jamaloddin Golestani',keywords:'Distributed scheduling'},
        {id:62,title:'Online Hedge Reservation for Diverse Plans and Competitive Analysis',authors:'Binghan Wu, Wei Bao, Dong Yuan and Bing Zhou',keywords:'competitive analysis'},
        {id:109,title:'Scheduling Stochastic Jobs - Complexity and Approximation Algorithms',authors:'Liangde Tao, Lin Chen and Guochuan Zhang',keywords:'approximation algorithm'},
        {id:238,title:'GRAND-VISION: An Intelligent System for Optimized Deployment Scheduling of Law Enforcement Agents',authors:'Jonathan Chase, Phong Tran, Long Kang, Tony Le and Hoong Chuin Lau',keywords:'Public Security'},
    ],
    [
        {id:48,title:'Explaining path plan optimality: fast explanation methods for navigation meshes using full and incremental inverse optimization',authors:'Martim Brandao, Amanda Coles and Daniele Magazzeni',keywords:'explainable planning'},
        {id:60,title:'Compositional Approach to Translate LTLf/LDLf into Deterministic Finite Automata',authors:'Giuseppe De Giacomo and Marco Favorito',keywords:'linear temporal logic on finite traces'},
        {id:219,title:'On Planning with Qualitative State-Trajectory Constraints in PDDL3 by Compiling them Away',authors:'Luigi Bonassi, Alfonso Emilio Gerevini, Francesco Percassi and Enrico Scala',keywords:'Compilation'},
        {id:306,title:'vPlanSim: An Open Source Graphical Interface for the Visualisation and Simulation of AI Systems',authors:'Jamie Roberts, Georgios Mastorakis, Brad Lazaruk, Santiago Franco, Adam Stokes and Sara Bernardini',keywords:'PDDL'},
    ],
    [
        {id:5,title:'Block Compression and Invariant Pruning for SAT-based Totally-Ordered HTN Planning',authors:'Gregor Behnke',keywords:'HTN Planning'},
        {id:38,title:'Translating Totally Ordered HTN Planning Problems to Classical Planning Problems Using Regular Approximation of Context-Free Languages',authors:'Daniel Höller',keywords:'HTN planning'},
        {id:44,title:'Fully Observable Nondeterministic HTN Planning -- Formalisation and Complexity Results',authors:'Dillon Chen and Pascal Bercher',keywords:'HTN Planning'},
        {id:49,title:'Loop Detection in the PANDA Planning System',authors:'Daniel Höller and Gregor Behnke',keywords:'HTN planning'},
    ],
    [
        {id:118,title:'Autonomous Building of Structures in Unstructured Environments via AI Planning',authors:'Jamie Roberts, Santiago Franco, Adam Stokes and Sara Bernardini',keywords:'Task Planning'},
        {id:130,title:'Knowledge Compilation for Nondeterministic Action Languages',authors:'Sergej Scheck, Alexandre Niveau and Bruno Zanuttini',keywords:'knowledge compilation'},
        {id:264,title:'Generalized Planning as Heuristic Search',authors:'Javier Segovia-Aguas, Sergio Jimenez Celorrio and Anders Jonsson',keywords:'Learning and deriving generalized plans'},
        {id:362,title:'What do you really want to do? Towards a Theory of Intentions for Human-Robot Collaboration',authors:'Mohan Sridharan, Rocio Gomez and Heather Riley',keywords:''},
    ],
    [
        {id:37,title:'A Closer Look at Causal Links: Complexity Results for Delete-Relaxation in Partial Order Causal Link (POCL) Planning',authors:'Pascal Bercher',keywords:'POP'},
        {id:143,title:'Decentralized Refinement Planning and Acting',authors:'Ruoxi Li, Sunandita Patra and Dana Nau',keywords:'Multi-agent systems'},
        {id:163,title:'Automated design of fMRI paradigms',authors:'Katherine Esper and Felipe Meneguzzi',keywords:'PDDL+'},
        {id:364,title:'Landmark-based approaches for goal recognition as planning',authors:'Ramon Fraga Pereira, Nir Oren and Felipe Meneguzzi',keywords:''},
    ],
    [
        {id:85,title:'Temporal Reasoning with Kinodynamic Networks',authors:'Han Zhang, Neelesh Tiruviluamala, Sven Koenig and T. K. Satish Kumar',keywords:'Temporal Reasoning'},
        {id:339,title:'PLGRIM: Hierarchical Value Learning for Large-scale Exploration in Unknown Environments',authors:'Sung-Kyun Kim, Amanda Bouman, Gautam Salhotra, David Fan, Kyohei Otsu, Joel Burdick and Aliakbar Aghamohammadi',keywords:'Large-scale exploration'},
        {id:365,title:'Self-Reliant Rovers for Increased Mission Productivity',authors:'Daniel Gaines, Gary Doran, Michael Paton, Brandon Rothrock, Joseph Russino, Ryan Mackey, Robert Anderson, Raymond Francis, Chet Joswig, Heather Justice, Ksenia Kolcio, Gregg Rabideau, Steve Schaffer, Jacek Sawoniewicz, Ashwin Vasavada and Ali-Akbar Agha-Mohammadi',keywords:''},
    ],
    [
        {id:338,title:'Computing Opportunities to Augment Plans for Novel Replanning during Execution',authors:'Daniel Borrajo and Manuela Veloso',keywords:'Planning with opportunities'},
        {id:367,title:'Adaptive Smoothing for Path Integral Control',authors:'Dominik Thalmeier, Hilbert J. Kappen, Simone Totaro and Vicenç Gómez',keywords:''},
    ]
]